#!/bin/bash
#echo "hello"
RAW_SCRIPT_NAME=$0
SCRIPT_NAME=${RAW_SCRIPT_NAME:2}

#manually do:
#		connect to wifi
#		change keymap
#		partition disks
#		format disks -> mkfs.ext4 mkswap
#		mount disks
#		(activate swap -> swapon)


### install options: ############################################

#INSTALL_MODE="legacy" #OPTIONS: legacy uefi

ROOT_DRIVE="/dev/sda"
ROOT_PART="/dev/sda1"
SWAP_PART="yes" #OPTIONS: yes no

KERNEL_TYPE="stable" #OPTIONS:stable zen lts

KEYMAP="cz-qwertz"

GPU_DRIVER="nvidia" #OPTIONS: nvidia amd intel vbox laptop
CPU_UCODE="intel" #OPTIONS: intel amd

LOGIN_MANAGER="lightdm" #OPTIONS: lightmd xinit 
DESKTOP="xmonad" #OPTIONS: xmonad xfce kde openbox fluxbox icewm

TIMEZONE_REGION="Europe"
TIMEZONE_CITY="Prague"

LOCALE_GEN_LANG_1="en_US.UTF8 UTF-8"
LOCALE_GEN_LANG_2="cs_CZ.UTF8 UTF-8"
LOCALE_LANG="${LOCALE_GEN_LANG_1::10}"
LOCALE_LC="${LOCALE_GEN_LANG_2::10}"

HOSTNAME="archbox"

ENABLE_SSH="1" #OPTIONS: 1=yes 0=no

ROOT_NAME="root"
ROOT_PASS="rootpass"

USER_NAME="fesoj"
USER_PASS="maturant"

#################################################################
packages=""
package_installer(){
	packages="$packages $1"
}

package_installer_clear(){
	packages=""
}

prechroot(){
	#case $SWAP_PART in
	#	yes) ;;
	#	no) ;;
	#esac

	case $KERNEL_TYPE in
		stable) KERNEL="linux linux-headers" ;; 	#stable kernel
		lts) KERNEL="linux-lts linux-lts-headers" ;;	#lts kernel
		zen) KERNEL="linux-zen linux-zen-headers" ;;	#zen kernel
	esac

	loadkeys $KEYMAP
	timedatectl set-ntp true
	mount $ROOT_PART /mnt
	pacstrap /mnt base base-devel linux-firmware $KERNEL
	genfstab -U /mnt >> /mnt/etc/fstab
	echo "Initial setup complete"
}

chrting(){
	cp $SCRIPT_NAME /mnt/$SCRIPT_NAME
	arch-chroot /mnt ./$SCRIPT_NAME -p 3
	echo "arch-chroot complete installer will now close"
	rm /mnt/$SCRIPT_NAME
	umount /mnt
	#reboot
}

install(){
	## GPU drivers ###########################################
	case $GPU_DRIVER in
		amd) packages="$packages xf86-video-amdgpu" ;;  #amd
		nvidia) packages="$packages nvidia nvidia-utils" ;; #nvidia
		intel) packages="$packages xf86-video-???" ;;  #intel
		laptop) packages="$packages  " ;; #intel+nvidia laptops
		vbox) packages="$packages xf86-video-fbdev" ;;    #vbox
	esac
	##########################################################

	## CPU Microcodes ########################################
	case $CPU_UCODE in 
		intel) packages="$packages intel-ucode" ;;  #intel
		amd) packages="$packages amd-ucode" ;;   #amd
	esac
	###########################################################

	## login manager (display manager) ########################
	case $LOGIN_MANAGER in
		lightdm) packages="$packages lightdm lightdm-gtk-greeter" ;; #lightdm
		xinit | startx) packages="$packages xorg-xinit"	;; #xinit/startx
	esac
	###########################################################

	## desktops ###############################################
	packages="$packages xorg" # X server itself
	case $DESKTOP in
		xmonad) packages="$packages xmonad xmonad-contrib xmobar" ;; #xmonad
		xfce | xfce4) packages="$packages xfce4 xfce4-goodies" ;; #xfce4
		kde | kdeplasma) ;;
		openbox) ;;
		fluxbox) ;;
		icewm) ;;
	esac
	###########################################################

	packages="$packages man-db man-pages texinfo"   #info pages
	packages="$packages mtools dosfstools"          #ms utils
	#packages="$packages git dialog whiptail"        #dev utils
	packages="$packages git dialog"  	        #dev utils
	packages="$packages xdg-user-dirs xdg-utils"    #xdg
	packages="$packages pulseaudio pavucontrol"     #audio
	packages="$packages networkmanager network-manager-applet openssh" #network
	packages="$packages wpa_supplicant iwd"		#network - wifi
	packages="$packages grub"                       #bootloader
	#packages="$packages zsh"                       #shell
	packages="$packages neovim emacs"               #text editor
	packages="$packages picom"                      #compositor
	packages="$packages kitty"                      #terminal
	packages="$packages nitrogen"                   #wallpaper setter
	packages="$packages rofi dmenu"                 #app launchers
	packages="$packages stow"			#dotfile management
	packages="$packages tmux"			#terminal multiplexer
	packages="$packages firefox qutebrowser"        #browser
	packages="$packages pcmanfm ranger"		#file manager

	#packages="$packages "

	#pacman -S --noconfirm $packages
	pacman -S $packages

	ln -sf /usr/share/zoneinfo/$TIMEZONE_REGION/$TIMEZONE_CITY /etc/localtime 
	hwclock --systohc
	echo "$LOCALE_GEN_LANG_1" >> /etc/locale.gen
	echo "$LOCALE_GEN_LANG_2" >> /etc/locale.gen
	locale-gen
	echo "LANG=$LOCALE_LANG" >> /etc/locale.conf
	#echo "LC_ALL=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_ADDRESS=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_IDENTIFICATION=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_MEASUREMENT=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_MONETARY=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_NAME=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_NUMERIC=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_PAPER=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_TELEPHONE=$LOCALE_LC" >> /etc/locale.conf
	echo "LC_TIME=$LOCALE_LC" >> /etc/locale.conf

	echo "KEYMAP=$KEYMAP" >> /etc/vconsole.conf

	echo "$HOSTNAME" >> /etc/hostname
	echo "127.0.0.1     localhost" >> /etc/hosts
	echo "::1           localhost" >> /etc/hosts
	echo "127.0.1.1     $HOSTNAME.localdomain $HOSTNAME" >> /etc/hosts

	systemctl enable NetworkManager
	systemctl enable lightdm
	[ $ENABLE_SSH -eq 1 ] && systemctl enable sshd
	mkinitcpio -P

	echo "$ROOT_NAME:$ROOT_PASS" | chpasswd

	ls /sys/firmware/efi/efivars 2> /dev/null > /dev/null
	[ $? -eq 0 ] && INSTALL_MODE=uefi || INSTALL_MODE=legacy

	case $INSTALL_MODE in 
		legacy) grub-install --target=i386-pc $ROOT_DRIVE ;;
		uefi) grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot ;;
	esac
	grub-mkconfig -o /boot/grub/grub.cfg

	echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
	#echo "%wheel ALL=(ALL) NOPASSWD: /usr/bin/shutdown,/usr/bin/reboot,/usr/bin/poweroff,/usr/bin/pacman -Syu" >> /etc/sudoers
	echo "Defaults !tty_tickets" >> /etc/sudoers

	useradd -m -G wheel $USER_NAME
	#useradd -m -G wheel -s /bin/zsh $USER_NAME
	echo "$USER_NAME:$USER_PASS" | chpasswd
	
	#chown -R $USER_NAME /home/$USER_NAME
	##chown -R $USER_NAME:$USER_NAME /home/$USER_NAME
}

setup(){
	#AUR
	cd /home/$USER_NAME
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg --noconfirm -si
	cd

	#japanese keyboard and language

        #echo "setxkbmap cz &" >> .xinitrc or .xprofile
	#echo "nitrogen --restore &" >> .xinitrc or .xprofile
	#echo "picom -f &" >> .xinitrc or .xprofile

	#mkdir .xmonad 
	#echo "import XMonad
	#main = xmonad def
	#	{ terminal = "kitty"
	#	, modMask = mod4Mask
	#	}" > .xmonad/xmonad.hs

	#bare git dotfiles - not used
	#mkdir -p /home/fesoj/git/public
	#cd /home/fesoj/git/public
	#git clone --bare https://github.com/Bokusekikan/dotfiles
	#git pull --git-dir=$HOME/git/public/dotfiles/ --work-tree=$HOME https://github.com/Bokusekikan/dofiles

	#GNU/stow dotfiles
	cd
	#mkdir -p git/public
	#cd git/public
	git clone https://github.com/Bokusekikan/dotfiles ~/git/public/dotfiles
	#cd dotfiles
	cd git/public/dotfiles
	stow -t ~/ .
	cd
}

rice(){
	#Download fonts
	#Apply fonts
	#Download theme
	#Apply theme
	#Download icon pack
	#Apply icon pack
	
	
	## COMMON PART ##
	
	## DE/WM SPECIFIC ##
	echo "this is rice"
}

usage(){
	stageunder="\033[04mSTAGE\033[0m"
	partunder="\033[04mPART\033[0m"
	echo -e "Usage:
	-h, --help
		Prints this help
	-p $partunder, --part $partunder
		Runs a specified part of the install script.
		AVAILABLE:
			1 or prechroot -> sets up few things before installation
			2 or chrting   -> copies this script to /mnt and executes part 3
			3 or install   -> installs the system
			4 or setup     -> installs dotfiles and aur
			5 or rice      -> applies rice to the system
	-s $stageunder, --stage $stageunder
		Runs a specified stage of the install script.
		AVAILABLE:
			1 or install -> installs the system (equivalent to parts 1 and 2) 
			2 or setup   -> sets up the environment (equivalent to parts 4 and 5)"
}

warning(){
	echo "Before running the script ensure the install options are reflecting your neeeds/wants and are compatible with your computer"

	echo "Run the script with: 
	$SCRIPT_NAME -s 1 OR $SCRIPT_NAME -s install	For installation of the system
	$SCRIPT_NAME -s 2 OR $SCRIPT_NAME -s setup	For setup of the user space/environment"

	echo "For help type $SCRIPT_NAME -h OR --help"
}

if [[ $# -eq 0 ]]; then
	warning
else
	case $1 in
		-p | --part)
			shift
			case $1 in 
				prechroot | 1) prechroot ;;
				chrting | 2) chrting ;;
				install | 3) install ;;
				setup | 4) setup ;;
				rice | 5) rice ;;
				*) echo "Unknown part" ;;
			esac 
			;;
		-s | --stage )
			shift
			case $1 in 
				install | 1)
					prechroot
					chrting
					#install
					;;
				setup | 2)
					setup
					rice
					;;
				*) echo "Unknown stage" ;;
			esac
			;;
			
		-h | --help ) usage ;;
		*) echo "Unknown choice" ;;
	esac	
fi
